# dungeon/dungeon.mk -- provided. Do not edit this file.
#
# Your Makefile includes it with one line:
#
#     include dungeon/dungeon.mk
#
# and gets three things:
#
#     $(DUNGEON)         the dungeon object file; link it into all four programs
#     $(DUNGEON_CFLAGS)  compile flags your .c files need to find dungeon_info.h
#     $(DUNGEON_LIBS)    libraries to link with (shared memory, threads)
#
# The dungeon is provided only as a compiled object, for Linux on x86_64:
# your Codespace.

DUNGEON_CFLAGS := -Idungeon
DUNGEON_LIBS   := -lrt -pthread

UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)

ifeq ($(UNAME_S)-$(UNAME_M),Linux-x86_64)
DUNGEON := dungeon/lib/dungeon_x86_64.o
else
$(error The dungeon runs only in your Codespace (Linux x86_64), and this machine is $(UNAME_S)/$(UNAME_M). See "Before you start" in the README)
endif

# Prints the id built into your dungeon. Compare it with the README.
.PHONY: dungeon-id
dungeon-id:
	@grep -a -o 'dungeon-id:[0-9A-F]\{8\}' $(DUNGEON) | head -1 | sed 's/dungeon-id:/dungeon id /'

# Let the first target in YOUR Makefile be the default, not the one above.
.DEFAULT_GOAL :=
